check_for_binary_files_without_source_code:
  comment: 'done'
check_for_remote_code_execution_in_javascript:
  comment: 'done'
check_for_builtin_functions:
  comment: 'done'
check_for_data_compression_and_archiving:
  comment: 'done'
check_for_file_and_directory_access:
  comment: 'done'
check_for_generic_operating_system_services:
  comment: 'done'
check_for_importing_modules:
  comment: 'done'
check_for_plain_text_credentials_in_python:
  comment: 'done'
check_for_environment_variable_use_in_python:
  comment: 'done'
check_for_secret_disclosure:
  comment: 'done'
check_for_executable_flag:
  comment: 'done'
check_for_known_vulnerabilities_in_third_party_libraries:
  comment: 'done'
check_embedded_links:
  comment: 'done'
check_for_auto_update_features:
  comment: 'done'
check_link_includes_contact_info:
  comment: 'done'
check_documented_included_open_source:
  comment: 'done'
check_editing_and_proofreading:
  comment: 'done'
check_authorization_credentials:
  comment: 'done'
check_for_stacktrace_returned_to_user:
  comment: 'done'
check_fs_writes:
  comment: 'done'
check_user_privileges:
  comment: 'done'
check_for_reverse_shells:
  comment: 'done'
check_requires_access_to_files_outside_apps_dir:
  comment: 'done'
check_for_offensive_material:
  comment: 'done'
check_dependencies:
  comment: 'done'
check_hard_coded_paths:
  comment: 'done'
