name: splunk-example-ta
services:
  server:
    container_name: server-example-ta
    build:
      context: server
      dockerfile: Dockerfile

  splunk:
    image: splunk/splunk:latest
    container_name: splunk-example-ta
    ports:
      - "8000:8000"
    environment:
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD:-Chang3d!}
      - SPLUNK_HEC_TOKEN=${SPLUNK_HEC_TOKEN:-4a8a737d-5452-426c-a6f7-106dca4e813f}
      - SPLUNK_START_ARGS=${SPLUNK_START_ARGS:---accept-license}
    volumes:
      - ./output/Splunk_TA_Example:/opt/splunk/etc/apps/Splunk_TA_Example
