services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  splunk:
    image: splunk/splunk:latest
    hostname: splunk
    ports:
      - "8000:8000"
      - "8088:8088"
      - "8089:8089"
    environment:
      - SPLUNK_PASSWORD=Chang3d!
      - SPLUNK_HEC_TOKEN=4a8a737d-5452-426c-a6f7-106dca4e813f
      - SPLUNK_START_ARGS=--accept-license
    volumes:
      - ./output/Splunk_TA_Example:/opt/splunk/etc/apps/Splunk_TA_Example
