PROBE_PROXY_CHECK_INTERVAL = 2  # in seconds
PROBE_PROXY_CHECK_TIMEOUT = 30  # in seconds
PROBE_LOGLEVEL_CHECK_INTERVAL = 2  # in seconds
PROBE_LOGLEVEL_CHECK_TIMEOUT = 30  # in seconds
TA_LOG_LEVEL_FOR_TESTS = "DEBUG"
ENCRYPTED_VALUE = "******"
INPUT_INTERVAL = 60
