on:
  push:
    branches:
      - "main"
      - "develop"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: pre-commit/action@v3.0.1

  build:
    needs:
      - pre-commit
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.7"
      - run: |
          python3 -m venv .venv
          source .venv/bin/activate
      - run: pip install -r requirements-dev.txt
      - run: ucc-gen build
      - uses: actions/upload-artifact@v4
        with:
          name: output
          path: output/
      - run: ucc-gen package --path output/Splunk_TA_Example
      - uses: actions/upload-artifact@v4
        with:
          name: Splunk_TA_Example
          path: Splunk_TA_Example*.tar.gz
